steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/order-service:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/order-service:latest',
      '-f', 'Dockerfile',
      '.'
    ]

images:
  - 'gcr.io/$PROJECT_ID/order-service:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/order-service:latest' 