name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}

jobs:
  setup-build-deploy:
    name: Setup, Build, Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        install_components: 'gke-gcloud-auth-plugin'

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and Push Cart Service
      run: |
        cd packages/cart-service
        docker build -t gcr.io/$PROJECT_ID/cart-service:$GITHUB_SHA .
        docker push gcr.io/$PROJECT_ID/cart-service:$GITHUB_SHA

    - name: Build and Push Order Service
      run: |
        cd packages/order-service
        docker build -t gcr.io/$PROJECT_ID/order-service:$GITHUB_SHA .
        docker push gcr.io/$PROJECT_ID/order-service:$GITHUB_SHA

    - name: Build and Push Inventory Service
      run: |
        cd packages/inventory-service
        docker build -t gcr.io/$PROJECT_ID/inventory-service:$GITHUB_SHA .
        docker push gcr.io/$PROJECT_ID/inventory-service:$GITHUB_SHA

    - name: Build and Push Notification Service
      run: |
        cd packages/notification-service
        docker build -t gcr.io/$PROJECT_ID/notification-service:$GITHUB_SHA .
        docker push gcr.io/$PROJECT_ID/notification-service:$GITHUB_SHA

    - name: Deploy Cart Service
      run: |
        gcloud run deploy cart-service \
          --image gcr.io/$PROJECT_ID/cart-service:$GITHUB_SHA \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars="DB_HOST=$DB_HOST,DB_PORT=$DB_PORT,DB_USER=$DB_USER,DB_PASSWORD=$DB_PASSWORD,DB_NAME=$DB_NAME,NODE_ENV=production"

    - name: Deploy Order Service
      run: |
        gcloud run deploy order-service \
          --image gcr.io/$PROJECT_ID/order-service:$GITHUB_SHA \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars="DB_HOST=$DB_HOST,DB_PORT=$DB_PORT,DB_USER=$DB_USER,DB_PASSWORD=$DB_PASSWORD,DB_NAME=$DB_NAME,NODE_ENV=production"

    - name: Deploy Inventory Service
      run: |
        gcloud run deploy inventory-service \
          --image gcr.io/$PROJECT_ID/inventory-service:$GITHUB_SHA \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars="DB_HOST=$DB_HOST,DB_PORT=$DB_PORT,DB_USER=$DB_USER,DB_PASSWORD=$DB_PASSWORD,DB_NAME=$DB_NAME,NODE_ENV=production"

    - name: Deploy Notification Service
      run: |
        gcloud run deploy notification-service \
          --image gcr.io/$PROJECT_ID/notification-service:$GITHUB_SHA \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars="DB_HOST=$DB_HOST,DB_PORT=$DB_PORT,DB_USER=$DB_USER,DB_PASSWORD=$DB_PASSWORD,DB_NAME=$DB_NAME,NODE_ENV=production" 