name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}

jobs:
  setup-build-deploy:
    name: Setup, Build, Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Verify Repository Structure
      run: |
        echo "Current directory structure:"
        pwd
        ls -la
        echo "\nShared directory contents:"
        ls -la shared/
        echo "\nShared config contents:"
        ls -la shared/config/
        echo "\nShared entities contents:"
        ls -la shared/entities/
        echo "\nShared types contents:"
        ls -la shared/types/
        echo "\nShared utils contents:"
        ls -la shared/utils/
        echo "\nCart service contents:"
        ls -la packages/cart-service/
        echo "\nShared package.json contents:"
        cat shared/package.json
        echo "\nCart service package.json contents:"
        cat packages/cart-service/package.json

    - name: Prepare Build Context
      run: |
        # Create temporary build context
        mkdir -p /tmp/build-context
        # Copy all necessary files
        cp -r . /tmp/build-context/
        # Verify the copy
        echo "Build context contents:"
        ls -la /tmp/build-context/
        echo "\nBuild context shared directory:"
        ls -la /tmp/build-context/shared/

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: 'gke-gcloud-auth-plugin'

    - name: Configure Docker
      run: |
        echo "Configuring Docker authentication..."
        gcloud auth configure-docker --quiet
        echo "Docker configuration complete"

    - name: Build and Push Cart Service
      run: |
        echo "Building Cart Service..."
        echo "Current directory: $(pwd)"
        echo "Build context contents:"
        ls -la /tmp/build-context/
        docker build \
          --no-cache \
          --build-arg DB_HOST=$DB_HOST \
          --build-arg DB_PORT=$DB_PORT \
          --build-arg DB_USER=$DB_USER \
          --build-arg DB_PASSWORD=$DB_PASSWORD \
          --build-arg DB_NAME=$DB_NAME \
          --build-arg NODE_ENV=production \
          -t gcr.io/$PROJECT_ID/cart-service:$GITHUB_SHA \
          -f packages/cart-service/Dockerfile \
          /tmp/build-context
        echo "Pushing Cart Service image..."
        docker push gcr.io/$PROJECT_ID/cart-service:$GITHUB_SHA

    - name: Build and Push Order Service
      run: |
        echo "Building Order Service..."
        docker build \
          --no-cache \
          --build-arg DB_HOST=$DB_HOST \
          --build-arg DB_PORT=$DB_PORT \
          --build-arg DB_USER=$DB_USER \
          --build-arg DB_PASSWORD=$DB_PASSWORD \
          --build-arg DB_NAME=$DB_NAME \
          --build-arg NODE_ENV=production \
          -t gcr.io/$PROJECT_ID/order-service:$GITHUB_SHA \
          -f packages/order-service/Dockerfile \
          /tmp/build-context
        echo "Pushing Order Service image..."
        docker push gcr.io/$PROJECT_ID/order-service:$GITHUB_SHA

    - name: Build and Push Inventory Service
      run: |
        echo "Building Inventory Service..."
        docker build \
          --no-cache \
          --build-arg DB_HOST=$DB_HOST \
          --build-arg DB_PORT=$DB_PORT \
          --build-arg DB_USER=$DB_USER \
          --build-arg DB_PASSWORD=$DB_PASSWORD \
          --build-arg DB_NAME=$DB_NAME \
          --build-arg NODE_ENV=production \
          -t gcr.io/$PROJECT_ID/inventory-service:$GITHUB_SHA \
          -f packages/inventory-service/Dockerfile \
          /tmp/build-context
        echo "Pushing Inventory Service image..."
        docker push gcr.io/$PROJECT_ID/inventory-service:$GITHUB_SHA

    - name: Build and Push Notification Service
      run: |
        echo "Building Notification Service..."
        docker build \
          --no-cache \
          --build-arg DB_HOST=$DB_HOST \
          --build-arg DB_PORT=$DB_PORT \
          --build-arg DB_USER=$DB_USER \
          --build-arg DB_PASSWORD=$DB_PASSWORD \
          --build-arg DB_NAME=$DB_NAME \
          --build-arg NODE_ENV=production \
          -t gcr.io/$PROJECT_ID/notification-service:$GITHUB_SHA \
          -f packages/notification-service/Dockerfile \
          /tmp/build-context
        echo "Pushing Notification Service image..."
        docker push gcr.io/$PROJECT_ID/notification-service:$GITHUB_SHA

    - name: Build and Push Product Service
      run: |
        echo "Building Product Service..."
        docker build \
          --no-cache \
          --build-arg DB_HOST=$DB_HOST \
          --build-arg DB_PORT=$DB_PORT \
          --build-arg DB_USER=$DB_USER \
          --build-arg DB_PASSWORD=$DB_PASSWORD \
          --build-arg DB_NAME=$DB_NAME \
          --build-arg NODE_ENV=production \
          -t gcr.io/$PROJECT_ID/product-service:$GITHUB_SHA \
          -f packages/product-service/Dockerfile \
          /tmp/build-context
        echo "Pushing Product Service image..."
        docker push gcr.io/$PROJECT_ID/product-service:$GITHUB_SHA

    - name: Build and Push Email Service
      run: |
        echo "Building Email Service..."
        docker build \
          --no-cache \
          --build-arg DB_HOST=$DB_HOST \
          --build-arg DB_PORT=$DB_PORT \
          --build-arg DB_USER=$DB_USER \
          --build-arg DB_PASSWORD=$DB_PASSWORD \
          --build-arg DB_NAME=$DB_NAME \
          --build-arg NODE_ENV=production \
          -t gcr.io/$PROJECT_ID/email-service:$GITHUB_SHA \
          -f packages/email-service/Dockerfile \
          /tmp/build-context
        echo "Pushing Email Service image..."
        docker push gcr.io/$PROJECT_ID/email-service:$GITHUB_SHA

    - name: Build and Push Customer Service
      run: |
        echo "Building Customer Service..."
        docker build \
          --no-cache \
          --build-arg DB_HOST=$DB_HOST \
          --build-arg DB_PORT=$DB_PORT \
          --build-arg DB_USER=$DB_USER \
          --build-arg DB_PASSWORD=$DB_PASSWORD \
          --build-arg DB_NAME=$DB_NAME \
          --build-arg NODE_ENV=production \
          -t gcr.io/$PROJECT_ID/customer-service:$GITHUB_SHA \
          -f packages/customer-service/Dockerfile \
          /tmp/build-context
        echo "Pushing Customer Service image..."
        docker push gcr.io/$PROJECT_ID/customer-service:$GITHUB_SHA

    - name: Deploy Cart Service
      run: |
        echo "Deploying Cart Service to Cloud Run..."
        gcloud run deploy cart-service \
          --image gcr.io/$PROJECT_ID/cart-service:$GITHUB_SHA \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars="DB_HOST=$DB_HOST,DB_PORT=$DB_PORT,DB_USER=$DB_USER,DB_PASSWORD=$DB_PASSWORD,DB_NAME=$DB_NAME,NODE_ENV=production"

    - name: Deploy Order Service
      run: |
        echo "Deploying Order Service to Cloud Run..."
        gcloud run deploy order-service \
          --image gcr.io/$PROJECT_ID/order-service:$GITHUB_SHA \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars="DB_HOST=$DB_HOST,DB_PORT=$DB_PORT,DB_USER=$DB_USER,DB_PASSWORD=$DB_PASSWORD,DB_NAME=$DB_NAME,NODE_ENV=production"

    - name: Deploy Inventory Service
      run: |
        echo "Deploying Inventory Service to Cloud Run..."
        gcloud run deploy inventory-service \
          --image gcr.io/$PROJECT_ID/inventory-service:$GITHUB_SHA \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars="DB_HOST=$DB_HOST,DB_PORT=$DB_PORT,DB_USER=$DB_USER,DB_PASSWORD=$DB_PASSWORD,DB_NAME=$DB_NAME,NODE_ENV=production"

    - name: Deploy Notification Service
      run: |
        echo "Deploying Notification Service to Cloud Run..."
        gcloud run deploy notification-service \
          --image gcr.io/$PROJECT_ID/notification-service:$GITHUB_SHA \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars="DB_HOST=$DB_HOST,DB_PORT=$DB_PORT,DB_USER=$DB_USER,DB_PASSWORD=$DB_PASSWORD,DB_NAME=$DB_NAME,NODE_ENV=production"

    - name: Deploy Product Service
      run: |
        echo "Deploying Product Service to Cloud Run..."
        gcloud run deploy product-service \
          --image gcr.io/$PROJECT_ID/product-service:$GITHUB_SHA \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars="DB_HOST=$DB_HOST,DB_PORT=$DB_PORT,DB_USER=$DB_USER,DB_PASSWORD=$DB_PASSWORD,DB_NAME=$DB_NAME,NODE_ENV=production"

    - name: Deploy Email Service
      run: |
        echo "Deploying Email Service to Cloud Run..."
        gcloud run deploy email-service \
          --image gcr.io/$PROJECT_ID/email-service:$GITHUB_SHA \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars="DB_HOST=$DB_HOST,DB_PORT=$DB_PORT,DB_USER=$DB_USER,DB_PASSWORD=$DB_PASSWORD,DB_NAME=$DB_NAME,NODE_ENV=production"

    - name: Deploy Customer Service
      run: |
        echo "Deploying Customer Service to Cloud Run..."
        gcloud run deploy customer-service \
          --image gcr.io/$PROJECT_ID/customer-service:$GITHUB_SHA \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars="DB_HOST=$DB_HOST,DB_PORT=$DB_PORT,DB_USER=$DB_USER,DB_PASSWORD=$DB_PASSWORD,DB_NAME=$DB_NAME,NODE_ENV=production"

    - name: Post Google Auth
      if: always()
      run: |
        echo "Cleaning up Google Auth..."

    - name: Post Checkout
      if: always()
      run: |
        echo "Cleaning up checkout..."

    - name: Complete job
      if: always()
      run: |
        echo "Deployment complete" 